version: 2
updates:
  # .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@maintainers"
    assignees:
      - "@maintainers"
    commit-message:
      prefix: "🔧"
      include: "scope"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "⚡"
      include: "scope"
    
  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/hosting/containers"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "🐳"
      include: "scope"

